for inc in /etc/logcenter/zsync-*.inc.conf; do
    source "$inc"
done

SSH_IDENTITY=/etc/logcenter/zsync.key
SSH_USER=zsync
BECOMEROOT=1

INCLUDES=(
    /etc/cron.d/logcenter-*
    /etc/[e]lasticsearch
    /etc/[k]eepalived
    /etc/logcenter
    /etc/logrotate.d/*logcenter*
    /etc/profile.d/logcenter-*
    /etc/rsyslog.d
    /etc/sysconfig/[e]lasticsearch
    /etc/systemd/system/[e]lasticsearch.service.d
    /etc/systemd/system/[r]syslog.service.d
    /etc/systemd/system/[s]igfiled.service
    /opt/logcenter
    /var/lib/[g]eoip
)

if [[ -L /var/lib/geoip ]]; then
    INCLUDES+=( $(readlink -f /var/lib/geoip) )
fi

EXCLUDES=(
    '.*.swp'
    /etc/elasticsearch/certs
    /etc/elasticsearch/elasticsearch.keystore
    /etc/elasticsearch/jvm.options*
    /etc/elasticsearch/trash
    /etc/elasticsearch/users
    /etc/elasticsearch/users_roles
    /etc/keepalived/logcenter.pref
    /etc/logcenter/certs/node.*
    /etc/logcenter/logcenter-local.inc.conf
    /etc/logcenter/zsync.key{,.pub}
)
