SSH_IDENTITY=/etc/logcenter/zsync.key
SSH_USER=zsync
BECOMEROOT=1

INCLUDES_collector=(
    /etc/keepalived/conf.d/logcenter-collector.*
    /etc/keepalived/conf.d/logcenter-parsing.*
    /etc/logcenter/certs/*-collector{,.bundle}.{crt,key,pem}
    /etc/logcenter/rsyslog/*.d
    /etc/logrotate.d/[l]ogcenter-rsyslog
    /etc/systemd/system/[r]syslog.service.d
)

INCLUDES_web=(
    /etc/haproxy/conf.d/*-{wui,archives,kibana}.cfg
    /etc/keepalived/conf.d/logcenter-web.*
    /etc/[k]ibana
    /etc/[l]ighttpd
    /etc/logcenter/certs/*-web{,.bundle}.{crt,key,pem}
    /etc/sysconfig/[h]aproxy
    /etc/systemd/system/[l]ighttpd.service.d
    /etc/systemd/system/[k]ibana.service.d
)

INCLUDES_archiver=(
    /etc/cron.d/[l]ogcenter-archives
    /etc/keepalived/conf.d/logcenter-archiver.*
    /etc/logcenter/certs/*-archiver{,.bundle}.{crt,key,pem}
    /etc/logcenter/rsyslog/*.d
    /etc/logrotate.d/[l]ogcenter-rsyslog
    /etc/systemd/system/[r]syslog.service.d
    /etc/systemd/system/[s]igfiled.service
)

INCLUDES_indexer=(
    /etc/cron.d/[l]ogcenter-es
    /etc/[e]lasticsearch
    /etc/haproxy/conf.d/*-elastic{,-*}.cfg
    /etc/keepalived/conf.d/logcenter-indexer.*
    /etc/logcenter/certs/*-{ingest,query}{,.bundle}.{crt,key,pem}
    /etc/[m]etricbeat
    /etc/profile.d/[l]ogcenter-es.sh
    /etc/sysconfig/[e]lasticsearch
    /etc/sysconfig/[h]aproxy
    /etc/systemd/system/[e]lasticsearch.service.d
    /etc/systemd/system/[m]etricbeat.service.d
    /var/lib/[g]eoip
)

INCLUDES_idxnode=(
    /etc/elasticsearch/users
    /etc/elasticsearch/users_roles
)

INCLUDES=(
    /etc/logcenter/certs/[c]a.crt
    /etc/logcenter/zsync*
    /etc/profile.d/[l]ogcenter-path.sh
    /etc/profile.d/[l]ogcenter-zsync.sh
    /opt/[l]ogcenter
)

EXCLUDES=(
    '.*.swp'
    '*.dist'
    '*.rpmnew'
    '*.rpmsave'
    /etc/elasticsearch/certs
    /etc/elasticsearch/elasticsearch.keystore
    '/etc/elasticsearch/jvm.options*'
    /etc/elasticsearch/trash
    '/etc/keepalived/logcenter-*.prefer'
    '/etc/keepalived/conf.d/logcenter-*.local'
    '/etc/keepalived/conf.d/logcenter-*.local.conf'
    /etc/kibana/.kibana.keystore.initial_md5sum
    /etc/kibana/kibana.keystore
    '/etc/logcenter/certs.*'
    '/etc/logcenter/certs/node.*'
    /etc/logcenter/logcenter-local.inc.conf
    /etc/logcenter/zlccli.key{,.pub}
    /etc/logcenter/zsync.key{,.pub}
    /etc/logcenter/zsync-local.inc.conf
    '/etc/logcenter/zsync-local-*.inc.conf'
)

for inc in /etc/logcenter/zsync-*.inc.conf; do
    source "$inc"
done

if [[ $ZSYNC_ROLE ]]; then
    v="INCLUDES_${ZSYNC_ROLE}[@]"; INCLUDES+=( "${!v}" )
    v="EXCLUDES_${ZSYNC_ROLE}[@]"; EXCLUDES+=( "${!v}" )
    v="PEERS_${ZSYNC_ROLE}[@]"; PEERS+=( "${!v}" )
else
    retval=0
    for i in collector archiver web indexer idxnode; do
        # skip if not my role
        v="PEERS_${i}[@]"; v=( "${!v,,}" )
        [[ ${v[*]/${HOSTNAME,,}} == ${v[*]} ]] && continue
        info "Logcenter role '$i'"
        ZSYNC_ROLE=$i "$0" "${ARGV[@]}"; role_retval=$?
        (( role_retval > retval )) && retval=$role_retval
    done
    exit $retval
fi
