SSH_IDENTITY=/etc/logcenter/zsync.key
SSH_USER=zsync
BECOMEROOT=1

INCLUDES=(
    /etc/cron.d/logcenter-*
    /etc/[e]lasticsearch
    /etc/[h]aproxy
    /etc/[k]eepalived
    /etc/[k]ibana
    /etc/logcenter
    /etc/logrotate.d/*logcenter*
    /etc/[m]etricbeat
    /etc/profile.d/logcenter-*
    /etc/rsyslog.d
    /etc/sysconfig/[e]lasticsearch
    /etc/sysconfig/[h]aproxy
    /etc/systemd/system/[e]lasticsearch.service.d
    /etc/systemd/system/[m]etricbeat.service.d
    /etc/systemd/system/[k]ibana.service.d
    /etc/systemd/system/[r]syslog.service.d
    /etc/systemd/system/[s]igfiled.service
    /opt/logcenter
    /var/lib/[g]eoip
)

if [[ -L /var/lib/geoip ]]; then
    INCLUDES+=( $(readlink -f /var/lib/geoip) )
fi

EXCLUDES=(
    '.*.swp'
    '*.dist'
    '*.rpmnew'
    '*.rpmsave'
    /etc/elasticsearch/certs
    /etc/elasticsearch/elasticsearch.keystore
    '/etc/elasticsearch/jvm.options*'
    /etc/elasticsearch/trash
    /etc/elasticsearch/users
    /etc/elasticsearch/users_roles
    '/etc/keepalived/logcenter-*.prefer'
    '/etc/keepalived/conf.d/logcenter-*.local'
    '/etc/keepalived/conf.d/logcenter-*.local.conf'
    /etc/kibana/.kibana.keystore.initial_md5sum
    /etc/kibana/kibana.keystore
    '/etc/logcenter/certs.*'
    '/etc/logcenter/certs/node.*'
    /etc/logcenter/logcenter-local.inc.conf
    /etc/logcenter/zsync.key{,.pub}
)

for inc in /etc/logcenter/zsync-*.inc.conf; do
    source "$inc"
done
