input(
    type="imfile"
    file="/var/log/elasticsearch/*_{audit,deprecation,index_{indexing,search}_slowlog,server}.json"
    readtimeout="5"
    persiststateinterval="100"
    deletestateonfiledelete="on"
    reopenontruncate="on"
    freshstarttail="on"
    tag="elasticsearch"
    severity="notice"
    facility="local0"
)

if ($inputname == "imfile" and $app-name == "elasticsearch") then {
    action(
        name="fwd-elasticsearch"
        type="omfwd"
        protocol="tcp"
        target="TARGET_HOST"
        port="TARGET_PORT"
        keepalive="on"
        keepalive.interval="10"
        keepalive.probes="3"
        template="RSYSLOG_SyslogProtocol23Format"
        action.resumeretrycount="-1"
        action.resumeinterval="10"
        action.reportsuspension="on"
        action.reportsuspensioncontinuation="on"
        queue.type="LinkedList"
        queue.size="1000"
        queue.timeoutenqueue="0"
        queue.maxfilesize="5m"
        queue.maxdiskspace="20m"
        queue.saveonshutdown="on"
        queue.filename="fwd-elasticsearch"
    )
    stop
}
