if ($fromhost-ip == ["127.0.0.1", "::1"]) then {
    action(
        name="fwd-external"
        type="omfwd"
        protocol="udp"
        target="EXTERNAL_LOG_HOST"
        port="EXTERNAL_LOG_PORT"
        template="RSYSLOG_SyslogProtocol23Format"
        action.resumeretrycount="-1"
        action.resumeinterval="10"
        action.reportsuspension="on"
        action.reportsuspensioncontinuation="on"
        queue.type="LinkedList"
        queue.size="5000"
        queue.timeoutenqueue="0"
    )
}
