##
## Copyright(C) 2024 @ ZENETYS
## License: MIT (http://opensource.org/licenses/MIT)
##

module(load="omrelp")

action(
    name="log-fwd-name"
    type="omrelp"
    target="log-fwd-target"
    port="2514"
    timeout="90"
    conn.timeout="10"
    template="template-forward-rfc5424-slash-srcip"

    # In case the HAProxy frontend switches to a backup
    # server, this allow to re-establish a connection
    # on the primary. Unit is in messages sent.
    rebindinterval="100000"

    action.resumeretrycount="-1"
    action.resumeinterval="5"
    action.resumeintervalmax="5"
    action.reportsuspension="on"
    action.reportsuspensioncontinuation="on"

    queue.type="LinkedList"
    queue.size="100000"
    queue.timeoutenqueue="5000"
    queue.dequeuebatchsize="8000"
    queue.workerthreads="2"
    queue.workerthreadminimummessages="30000"

    # disk assisted queue
    queue.spooldirectory="/var/lib/rsyslog"
    queue.maxfilesize="25m"
    queue.maxdiskspace="1g"
    queue.saveonshutdown="on"
    queue.filename="log-fwd-name"
)
