if ($app-name == "haproxy") then {
    action(
        type="omfile"
        file="/var/log/haproxy.log"
        template="RSYSLOG_FileFormat"
        name="logfile-haproxy"
        queue.type="LinkedList"
        queue.size="1000"
        queue.timeoutenqueue="0"
    )
    stop
}
