server.use-ipv6 := "disable"
server.bind = env.HOSTNAME
server.port := 8443

server.tag = ""

server.modules += (
    "mod_alias",
    "mod_cgi",
    "mod_openssl",
)

ssl.engine  = "enable"
ssl.ca-file = "/etc/logcenter/certs/ca.crt"
ssl.pemfile = "/etc/logcenter/certs/node.crt"
ssl.privkey = "/etc/logcenter/certs/node.key"

cgi.execute-x-only = "enable"
cgi.limits = (
    "write-timeout" => 15,
    "read-timeout" => 15,
    "tcp-fin-propagate" => "SIGTERM",
)

$HTTP["user-agent"] == "haproxy-check" { accesslog.filename = "" }
