# api

alias.url += (
    "/archives/api/list-archives" => "/opt/logcenter/lib/cgi-bin/list-archives.cgi",
    "/archives/api/list-indices" => "/opt/logcenter/lib/cgi-bin/list-indices.cgi",
    "/archives/api/get-archives" => "/opt/logcenter/lib/cgi-bin/get-archives.cgi",
    "/archives/config.json" => "/opt/logcenter/lib/cgi-bin/get-config.cgi",
    "/archives/api/config" => "/opt/logcenter/lib/cgi-bin/set-config.cgi",
)
$HTTP["url"] =~ "^/archives/api/list-archives" { cgi.assign = ( "" => "" ) }
$HTTP["url"] =~ "^/archives/api/list-indices" { cgi.assign = ( "" => "" ) }
$HTTP["url"] =~ "^/archives/api/get-archives" { cgi.assign = ( "" => "" ) }
$HTTP["url"] =~ "^/archives/api/config" { cgi.assign = ( "" => "" ) }
$HTTP["url"] =~ "^/archives/config.json" { cgi.assign = ( "" => "" ) }

# static
alias.url += ( "/archives/" => "/opt/logcenter/share/www/archives/" )
