global_defs {
  notification_email {
    root
  }
  notification_email_from root
  smtp_server 127.0.0.1
  script_user nobody
  enable_script_security
}

include logcenter.inc.conf

vrrp_script check_proc_rsyslog {
  script "/usr/bin/killall -0 rsyslogd"
  interval 2
  weight -10
  fall 6
  rise 1
}

vrrp_script check_proc_snmptrapd {
  script "/usr/bin/killall -0 snmptrapd"
  interval 2
  weight -10
  fall 6
  rise 1
}

vrrp_script preferred {
  script "/usr/bin/test -e /etc/keepalived/logcenter.pref"
  interval 30
  weight -5
}

vrrp_instance vrrp0 {
  virtual_router_id ${ZLC_VIRTUAL_ROUTER_ID}

  state BACKUP
  priority 100

  interface ${ZLC_INTERFACE}
  advert_int 1
  garp_master_delay 30

  authentication {
    auth_type PASS
    auth_pass ${ZLC_AUTH_PASS}
  }

  virtual_ipaddress {
    ${ZLC_VIRTUAL_ADDRESS}
  }

  track_script {
    preferred
    check_proc_rsyslog
    check_proc_snmptrapd
  }
}
