include logcenter-kibana.vars
include logcenter-kibana.vars.[l]ocal

vrrp_track_process zlc_kibana_check_haproxy {
  process haproxy
  terminate_delay 10
  weight -10
}

vrrp_script zlc_kibana_check_prefer {
  script "/usr/bin/test -e /etc/keepalived/logcenter-kibana.prefer"
  interval 30
  weight -5
}

vrrp_instance zlc_kibana_vrrp {
  virtual_router_id ${ZLC_KIBANA_VRID}
  state BACKUP
  priority 100
  interface ${ZLC_KIBANA_IFACE}
  advert_int 1
  garp_master_delay 30
  authentication {
    auth_type PASS
    auth_pass ${ZLC_KIBANA_PASS}
  }
  virtual_ipaddress {
    ${ZLC_KIBANA_VIP}
  }
  track_process {
    zlc_kibana_check_haproxy
  }
  track_script {
    zlc_kibana_check_prefer
  }
  notify /opt/logcenter/libexec/keepalived-notify-state root
}
