include logcenter-archiver.vars
include logcenter-archiver.vars.[l]ocal

vrrp_track_process zlc_archiver_check_rsyslogd {
  process "rsyslogd"
  terminate_delay 10
  weight -10
}

vrrp_script zlc_archiver_check_prefer {
  script "/usr/bin/test -e /etc/keepalived/logcenter-archiver.prefer"
  interval 30
  weight -5
}

vrrp_instance zlc_archiver_vrrp {
  virtual_router_id ${ZLC_ARCHIVER_VRID}
  state BACKUP
  priority 100
  interface ${ZLC_ARCHIVER_IFACE}
  advert_int 1
  garp_master_delay 30
  authentication {
    auth_type PASS
    auth_pass ${ZLC_ARCHIVER_PASS}
  }
  virtual_ipaddress {
    ${ZLC_ARCHIVER_VIP}
  }
  track_process {
    zlc_archiver_check_rsyslogd
  }
  track_script {
    zlc_archiver_check_prefer
  }
}
