include logcenter-web.vars
include logcenter-web.vars.[l]ocal

vrrp_track_process zlc_web_check_haproxy {
  process haproxy
  terminate_delay 10
  weight -10
}

vrrp_script zlc_web_check_prefer {
  script "/usr/bin/test -e /etc/keepalived/logcenter-web.prefer"
  interval 30
  weight -5
}

vrrp_instance zlc_web_vrrp {
  virtual_router_id ${ZLC_WEB_VRID}
  state BACKUP
  priority 100
  interface ${ZLC_WEB_IFACE}
  advert_int 1
  garp_master_delay 30
  authentication {
    auth_type PASS
    auth_pass ${ZLC_WEB_PASS}
  }
  virtual_ipaddress {
    ${ZLC_WEB_VIP}
  }
  track_process {
    zlc_web_check_haproxy
  }
  track_script {
    zlc_web_check_prefer
  }
}
