include logcenter-parsing.vars
include logcenter-parsing.vars.[l]ocal

vrrp_track_process zlc_parsing_check_rsyslogd {
  process "rsyslogd"
  terminate_delay 10
  weight -10
}

vrrp_script zlc_parsing_check_prefer {
  script "/usr/bin/test -e /etc/keepalived/logcenter-parsing.prefer"
  interval 30
  weight -5
}

vrrp_instance zlc_parsing_vrrp {
  virtual_router_id ${ZLC_PARSING_VRID}
  state BACKUP
  priority 100
  interface ${ZLC_PARSING_IFACE}
  advert_int 1
  garp_master_delay 30
  authentication {
    auth_type PASS
    auth_pass ${ZLC_PARSING_PASS}
  }
  virtual_ipaddress {
    ${ZLC_PARSING_VIP}
  }
  track_process {
    zlc_parsing_check_rsyslogd
  }
  track_script {
    zlc_parsing_check_prefer
  }
  notify /opt/logcenter/libexec/keepalived-notify-state root
}
