include logcenter-collector.vars
include logcenter-collector.vars.[l]ocal

vrrp_track_process zlc_collector_check_rsyslogd {
  process "rsyslogd"
  terminate_delay 10
  weight -10
}

vrrp_track_process zlc_collector_check_snmptrapd {
  process "snmptrapd"
  terminate_delay 10
  weight -10
}

vrrp_script zlc_collector_check_prefer {
  script "/usr/bin/test -e /etc/keepalived/logcenter-collector.prefer"
  interval 30
  weight -5
}

vrrp_instance zlc_collector_vrrp {
  virtual_router_id ${ZLC_COLLECTOR_VRID}
  state BACKUP
  priority 100
  interface ${ZLC_COLLECTOR_IFACE}
  advert_int 1
  garp_master_delay 30
  authentication {
    auth_type PASS
    auth_pass ${ZLC_COLLECTOR_PASS}
  }
  virtual_ipaddress {
    ${ZLC_COLLECTOR_VIP}
  }
  track_process {
    zlc_collector_check_rsyslogd
    zlc_collector_check_snmptrapd
  }
  track_script {
    zlc_collector_check_prefer
  }
  notify /opt/logcenter/libexec/keepalived-notify-state root
}
