include logcenter-indexer.vars
include logcenter-indexer.vars.[l]ocal

vrrp_track_process zlc_indexer_check_haproxy {
  process "haproxy"
  terminate_delay 10
  weight -10
}

vrrp_script zlc_indexer_check_prefer_ingest {
  script "/usr/bin/test -e /etc/keepalived/logcenter-indexer-ingest.prefer"
  interval 30
  weight -5
}

vrrp_script zlc_indexer_check_prefer_query {
  script "/usr/bin/test -e /etc/keepalived/logcenter-indexer-query.prefer"
  interval 30
  weight -5
}

vrrp_instance zlc_indexer_vrrp_ingest {
  virtual_router_id ${ZLC_INDEXER_INGEST_VRID}
  state BACKUP
  priority 100
  interface ${ZLC_INDEXER_INGEST_IFACE}
  advert_int 1
  garp_master_delay 30
  authentication {
    auth_type PASS
    auth_pass ${ZLC_INDEXER_INGEST_PASS}
  }
  virtual_ipaddress {
    ${ZLC_INDEXER_INGEST_VIP}
  }
  track_process {
    zlc_indexer_check_haproxy
  }
  track_script {
    zlc_indexer_check_prefer_ingest
  }
  notify /opt/logcenter/libexec/keepalived-notify-state root
}

vrrp_instance zlc_indexer_vrrp_query {
  virtual_router_id ${ZLC_INDEXER_QUERY_VRID}
  state BACKUP
  priority 100
  interface ${ZLC_INDEXER_QUERY_IFACE}
  advert_int 1
  garp_master_delay 30
  authentication {
    auth_type PASS
    auth_pass ${ZLC_INDEXER_QUERY_PASS}
  }
  virtual_ipaddress {
    ${ZLC_INDEXER_QUERY_VIP}
  }
  track_process {
    zlc_indexer_check_haproxy
  }
  track_script {
    zlc_indexer_check_prefer_query
  }
  notify /opt/logcenter/libexec/keepalived-notify-state root
}
