version=2

##
## Copyright(C) 2024 @ ZENETYS
## License: MIT (http://opensource.org/licenses/MIT)
##

type=@string:%{
    "type": "alternative",
    "parser": [
        { "type": "string", "name": "..", "quoting.mode": "required", "matching.mode": "lazy" },
        { "type": "char-sep", "name": "..", "extradata": "," }
     ] }%

# TRAFFIC
rule=:%[
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "TRAFFIC" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsrc", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdst", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcuser", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstuser", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "from", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "to", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "inbound_if", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "outbound_if", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "logset", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sessionid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "repeatcnt", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "flags", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "proto", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "action", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "bytes", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "bytes_sent", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "bytes_received", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "packets", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "start", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "elapsed", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcloc", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstloc", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pkts_sent", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pkts_received", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "session_end_reason", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "action_source", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_uuid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_uuid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnelid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "monitortag", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_session_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_start_time", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnel", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "assoc_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "chunks", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "chunks_sent", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "chunks_received", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule_uuid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http2_connection", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "link_change_count", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "policy_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "link_switches", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_cluster", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_device_type", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_cluster_type", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_site", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dynusergroup_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "xff_ip", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_category", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_profile", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_model", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_vendor", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osfamily", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osversion", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_host", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_mac", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_category", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_profile", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_model", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_vendor", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osfamily", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osversion", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_host", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_mac", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_namespace", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_edl", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_edl", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "hostid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serialnumber", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_dag", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_dag", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "session_owner", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "nsdsai_sst", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "nsdsai_sd", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subcategory_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "technology_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "risk_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "characteristic_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunneled_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "is_saas_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sanctioned_state_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "offloaded", "extradata": "," } ]%

# THREAT
rule=:%[
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "THREAT" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsrc", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdst", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcuser", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstuser", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "from", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "to", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "inbound_if", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "outbound_if", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "logset", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sessionid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "repeatcnt", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdport", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "flags", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "proto", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "action", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "misc", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "threatid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "severity", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "direction", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcloc", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstloc", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "contenttype", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pcap_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "filedigest", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "cloud", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "url_idx", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "user_agent", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "filetype", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "xff", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "referer", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sender", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subject", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "recipient", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "reportid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_uuid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_uuid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http_method", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnel_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "monitortag", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_session_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_start_time", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnel", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "thr_category", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "contentver", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "assoc_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "ppid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http_headers", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "url_category_list", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule_uuid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http2_connection", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dynusergroup_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "xff_ip", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_category", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_profile", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_model", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_vendor", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osfamily", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osversion", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_host", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_mac", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_category", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_profile", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_model", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_vendor", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osfamily", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osversion", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_host", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_mac", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_namespace", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_edl", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_edl", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "hostid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serialnumber", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "domain_edl", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_dag", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_dag", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "partial_hash", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "reason", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "justification", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "nssai_sst", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subcategory_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "technology_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "risk_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "characteristic_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunneled_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "is_saas_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sanctioned_state_of_app", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "cloud_reportid", "extradata": "," } ]%

# SYSTEM
rule=:%[
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "SYSTEM" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "eventid", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "object", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "module", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "severity", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "opaque", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp", "extradata": "," } ]%

# CONFIG
rule=:%[
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "CONFIG" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "host", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "cmd", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "admin", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "client", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "result", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "path", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_id", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "comment", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "extradata": "," }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp", "extradata": "," } ]%
