version=2

##
## Copyright(C) 2024 @ ZENETYS
## License: MIT (http://opensource.org/licenses/MIT)
##

type=@string:%{
    "type": "alternative",
    "parser": [
        { "type": "string", "name": "..", "quoting.mode": "required", "matching.mode": "lazy", "priority": 200 },
        { "type": "char-sep", "name": "..", "extradata": ",", "priority": 600 }
     ]
}%

type=@nothing:%[]%

type=@traffic_fields_v11_1:%[
    { "type": "literal", "text": "," }, { "type": "@string", "name": "flow_type" },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "cluster_name" },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "ai_traffic" },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "ai_fwd_error" },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "k8s_cluster_id" },
]%

type=@traffic_fields_v11_1_internal_telemetry:%[
    { "type": "@traffic_fields_v11_1", "name": "." },
    { "type": "literal", "text": "," }, { "type": "@string" },
    { "type": "literal", "text": "," }, { "type": "@string" },
    { "type": "literal", "text": "," }, { "type": "@string" },
    { "type": "literal", "text": "," }, { "type": "@string" },
    { "type": "literal", "text": "," }, { "type": "@string" },
    { "type": "literal", "text": "," }, { "type": "@string" },
    { "type": "literal", "text": "," }, { "type": "@string" },
    { "type": "literal", "text": "," }, { "type": "@string" },
]%

type=@traffic_fields_v12_1_2:%[
    { "type": "@traffic_fields_v11_1_internal_telemetry", "name": "." },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "src_adv_dev_id" },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "dst_adv_dev_id" }
]%

type=@traffic_fields_after_offloaded:%{
    "type": "alternative",
    "parser": [
        { "type": "@traffic_fields_v12_1_2", "name": ".", "priority": 200 },
        { "type": "@traffic_fields_v11_1_internal_telemetry", "name": ".", "priority": 300 },
        { "type": "@traffic_fields_v11_1", "name": ".", "priority": 400 },
        { "type": "@nothing", "name": ".", "priority": 500 },
     ]
}%

# TRAFFIC
rule=:%[
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial" }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "TRAFFIC" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsrc" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdst" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcuser" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstuser" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "from" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "to" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "inbound_if" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "outbound_if" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "logset" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sessionid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "repeatcnt" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "flags" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "proto" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "action" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "bytes" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "bytes_sent" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "bytes_received" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "packets" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "start" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "elapsed" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcloc" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstloc" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pkts_sent" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pkts_received" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "session_end_reason" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "action_source" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_uuid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_uuid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnelid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "monitortag" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_session_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_start_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnel" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "assoc_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "chunks" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "chunks_sent" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "chunks_received" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule_uuid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http2_connection" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "link_change_count" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "policy_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "link_switches" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_cluster" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_device_type" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_cluster_type" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sdwan_site" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dynusergroup_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "xff_ip" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_category" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_profile" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_model" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_vendor" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osfamily" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osversion" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_host" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_mac" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_category" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_profile" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_model" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_vendor" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osfamily" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osversion" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_host" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_mac" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_namespace" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_edl" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_edl" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "hostid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serialnumber" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_dag" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_dag" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "session_owner" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "nssai_sst" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "nssai_sd" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subcategory_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "technology_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "risk_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "characteristic_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunneled_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "is_saas_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sanctioned_state_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "offloaded" },
    { "type": "@traffic_fields_after_offloaded", "name": "." },
    { "type": "rest" } ]%

type=@threat_fields_v10_2:%[
    { "type": "literal", "text": "," }, { "type": "@string", "name": "cloud_reportid" },
]%

type=@threat_fields_v11_1:%[
    { "type": "@threat_fields_v10_2", "name": "." },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "cluster_name" },
    { "type": "literal", "text": "," }, { "type": "@string", "name": "flow_type" }
]%

type=@threat_fields_after_sanctioned_state_of_app:%{
    "type": "alternative",
    "parser": [
        { "type": "@threat_fields_v11_1", "name": ".", "priority": 200 },
        { "type": "@threat_fields_v10_2", "name": ".", "priority": 400 },
        { "type": "@nothing", "name": ".", "priority": 500 },
     ]
}%

# THREAT
rule=:%[
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial" }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "THREAT" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsrc" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdst" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcuser" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstuser" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "from" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "to" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "inbound_if" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "outbound_if" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "logset" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sessionid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "repeatcnt" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natsport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "natdport" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "flags" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "proto" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "action" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "misc" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "threatid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "severity" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "direction" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcloc" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dstloc" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "contenttype" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pcap_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "filedigest" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "cloud" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "url_idx" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "user_agent" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "filetype" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "xff" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "referer" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sender" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subject" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "recipient" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "reportid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_uuid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_uuid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http_method" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnel_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "monitortag" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_session_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "parent_start_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnel" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "thr_category" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "contentver" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "assoc_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "ppid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http_headers" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "url_category_list" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "rule_uuid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "http2_connection" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dynusergroup_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "xff_ip" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_category" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_profile" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_model" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_vendor" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osfamily" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_osversion" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_host" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_mac" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_category" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_profile" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_model" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_vendor" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osfamily" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_osversion" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_host" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_mac" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_namespace" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "pod_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_edl" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_edl" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "hostid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serialnumber" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "domain_edl" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "src_dag" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dst_dag" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "partial_hash" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "reason" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "justification" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "nssai_sst" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subcategory_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "category_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "technology_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "risk_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "characteristic_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "container_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunneled_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "is_saas_of_app" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "sanctioned_state_of_app" },
    { "type": "@threat_fields_after_sanctioned_state_of_app", "name": "." },
    { "type": "rest" } ]%

# SYSTEM
rule=:%[
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial" }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "SYSTEM" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "eventid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "object" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "module" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "severity" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "opaque" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp" },
    { "type": "rest" } ]%

# CONFIG
rule=:%[
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial" }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "CONFIG" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "time_generated" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "host" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "cmd" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "admin" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "client" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "result" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "path" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_id" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "comment" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "high_res_timestamp" },
    { "type": "rest" } ]%

type=@globalprotect_fields_v11_1:%[
    { "type": "literal", "text": "," }, { "type": "@string", "name": "cluster_name" },
]%

type=@globalprotect_fields_after_vsys_id:%{
    "type": "alternative",
    "parser": [
        { "type": "@globalprotect_fields_v11_1", "name": ".", "priority": 200 },
        { "type": "@nothing", "name": ".", "priority": 500 },
     ]
}%

# GLOBALPROTECT
rule=:%[
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "receive_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serial" }, { "type": "literal", "text": "," },
    { "type": "literal", "name": "type", "text": "GLOBALPROTECT" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "subtype" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "eventid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "stage" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "auth_method" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "tunnel_type" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcuser" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "srcregion" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "machinename" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "public_ip" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "public_ipv6" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "private_ip" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "private_ipv6" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "hostid" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "serialnumber" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "client_ver" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "client_os" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "client_os_ver" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "repeatcnt" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "reason" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "error" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "opaque" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "status" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "location" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "login_duration" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "connect_method" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "error_code" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "portal" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "seqno" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "actionflags" }, { "type": "literal", "text": "," },
    { "type": "@string" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "selection_type" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "response_time" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "priority" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "attempted_gateways" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "gateway" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_1" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_2" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_3" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "dg_hier_level_4" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "device_name" }, { "type": "literal", "text": "," },
    { "type": "@string", "name": "vsys_id" },
    { "type": "@globalprotect_fields_after_vsys_id", "name": "." },
    { "type": "rest" } ]%
