#DESTDIR=/var/backup/logcenter
#KEEPCOUNT=30

# logcenter-backup --help prints the list of backup items
#INCLUDE[item]=1
#EXCLUDE[item]=1

[[ -f /etc/profile.d/logcenter-path.sh ]] &&
    source /etc/profile.d/logcenter-path.sh
[[ -f /etc/profile.d/logcenter-es.sh ]] &&
    source /etc/profile.d/logcenter-es.sh
