LIBLOGNORM_RULEBASES=/opt/logcenter/lib/rsyslog/rulebase
RSYSLOG_DEBUGLOG=/var/log/logcenter/rsyslog.debug
ZLC_CONFIG_DIR_SYSTEM=/opt/logcenter/lib/rsyslog
ZLC_CONFIG_DIR_LOCAL=/etc/logcenter/rsyslog
ZLC_LOG_DIR=/var/log/logcenter
ZLC_MAX_MESSAGE_SIZE=32768
ZLC_LOAD_UNFLATTEN=on
ZLC_USE_DNS=off
ZLC_LISTEN_UXSOCK=off
ZLC_LISTEN_UXSOCK_SOCKET=/dev/log
ZLC_LISTEN_UDP=off
ZLC_LISTEN_UDP_ADDRESS=0.0.0.0
ZLC_LISTEN_UDP_PORT=514
ZLC_LISTEN_TCP=off
ZLC_LISTEN_TCP_ADDRESS=0.0.0.0
ZLC_LISTEN_TCP_PORT=514
ZLC_LISTEN_RELP=off
ZLC_LISTEN_RELP_ADDRESS=0.0.0.0
ZLC_LISTEN_RELP_PORT=2514
ZLC_PARSING_UNFLATTEN=on
ZLC_PARSING_LOAD_ALL_PARSERS=off
ZLC_OUTPUT_LOGMATCH=off
ZLC_OUTPUT_LOGMATCH_CONFIG=/var/lib/kompot/configs/logmatch/current/logmatch.conf
ZLC_OUTPUT_LOGMATCH_ALIASES=/var/lib/kompot/configs/logmatch/current/aliases.conf
ZLC_OUTPUT_LOGMATCH_NAGIOS_EXTERNAL_COMMAND_FILE=/var/spool/nagios/cmd/nagios.cmd
ZLC_OUTPUT_ARCHIVES=off
ZLC_OUTPUT_ARCHIVES_DIR=/var/log/network
ZLC_OUTPUT_ARCHIVES_USER=root
ZLC_OUTPUT_ARCHIVES_GROUP=adm
ZLC_OUTPUT_ELASTIC=off
ZLC_OUTPUT_ELASTIC_SERVER=https://127.0.0.1/fake-es
ZLC_OUTPUT_ELASTIC_CACERT=/dev/null
ZLC_OUTPUT_ELASTIC_UID=elastic
ZLC_OUTPUT_ELASTIC_PWD=password
ZLC_OUTPUT_ELASTIC_INSECURE=on
ZLC_OUTPUT_ELASTIC_NAMESPACE=lc
ZLC_OUTPUT_ELASTIC_REINJECT=off
ZLC_OUTPUT_ELASTIC_REINJECT_SERVER=https://127.0.0.1:9200
ZLC_OUTPUT_DEBUG=off
ZLC_NETWORK_STOP_AFTER_OUTPUTS=on
#ZLC_SIGFILED_SOCKNAME=/dev/shm/sigfiled.sock
ZLC_SIGFILED_KEYFILE=/etc/logcenter/sigfiled.key
ZLC_SIGFILED_PUBKEYFILE=/etc/logcenter/sigfiled.pubkey

if [[ -f /etc/logcenter/logcenter-local.inc.conf ]]; then
    source /etc/logcenter/logcenter-local.inc.conf
fi
