MODE=elastic
#MAXMIND_KEY=
#PRECMD=_pre
#POSTCMD=_post
PROXY=

[[ -f /etc/profile.d/logcenter-path.sh ]] &&
    source /etc/profile.d/logcenter-path.sh
[[ -f /etc/profile.d/logcenter-zsync.sh ]] &&
    source /etc/profile.d/logcenter-zsync.sh

function _pre() {
    REPLY=$(es-curl _cat/nodes)
    (( $? == 0 )) || { echo 'es-curl _cat/nodes failed'; return 1; }
    REPLY=$(echo "$REPLY" |awk -v "me=$HOSTNAME" '
        $(NF-1) == "*" && $NF == me { print "master" }')
    [[ $REPLY == master ]] || { echo 'not on master node'; return 1; }
    return 0
}

function _post() {
    # suitable for a ingest.geoip.downloader.endpoint exposed via http
    info 'Call elasticsearch-geoip'
    exec_quiet /usr/share/elasticsearch/bin/elasticsearch-geoip -s "$DESTDIR" || return 1
    # keep raw mmdb files by default
    #info 'Cleanup mmdb files'
    #find "$DESTDIR/" -name '*.mmdb' -delete
    info 'Sync to peers'
    local destdir=$(readlink -f "$DESTDIR")
    [[ -z $destdir ]] && { error 'readlink of DESTDIR failed'; return 1; }
    zsync -i "$destdir" -f < /dev/null
}
